Added Int32 type support when binding parameter
IBM-Swift/Swift-Kuery-SQLite pull request #11
Opened 2018-05-12 23:06 UTC by eugeniobaglieri

This commit resolve an “Unsupported type error” when a query contains an Int32 bindend parameter

2018-05-12 23:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM-Swift/Swift-Kuery-SQLite?pullRequest=11) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM-Swift/Swift-Kuery-SQLite?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM-Swift/Swift-Kuery-SQLite?pullRequest=11) it.</sub>

2018-05-31 14:20 UTC, EnriqueL8 approved these changes

2018-06-04 15:15 UTC, EnriqueL8 requested changes

2018-06-04 15:15 UTC, EnriqueL8 commented on Sources/SwiftKuerySQLite/SQLiteConnection.swift
> +            case let value as  Int32:
Extra space between `as` and `Int32`

2018-06-04 15:49 UTC, eugeniobaglieri commented on Sources/SwiftKuerySQLite/SQLiteConnection.swift
> +            case let value as  Int32:
done

2018-06-04 15:56 UTC, EnriqueL8 approved these changes

2018-06-07 12:38 UTC, merged